{{- $KafkaOperator := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "kafkas.kafka.strimzi.io" -}}
{{- if $KafkaOperator }}
# Service account for copying secrets between kafka namespace to <some_product> namespace.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: copy-secrets-sa
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-12"
---
# role for copying secrets from kafka namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: copy-secrets-role-{{ .Values.global.kafka_ns }}
  namespace: {{ .Values.global.kafka_ns }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-11"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: copy-secrets-rolebinding-{{ .Values.global.kafka_ns }}
  namespace: {{ .Values.global.kafka_ns }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
subjects:
  - kind: ServiceAccount
    name: copy-secrets-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: copy-secrets-role-{{ .Values.global.kafka_ns }}
  apiGroup: rbac.authorization.k8s.io



---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: copy-secrets-role-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: copy-secrets-rolebinding-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
subjects:
- kind: ServiceAccount
  name: copy-secrets-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: copy-secrets-role-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}